{% set version = "0.4.3" %}

package:
  name: runtime-introspect
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/r/runtime-introspect/runtime_introspect-{{ version }}.tar.gz
  sha256: 698e5db7f4c5f5b990554a93b10d1a3ecfc5319d7280380ee3b4430bcefbeba8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - runtime_introspect
  commands:
    - pip check
    - pytest -ra tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/neutrinoceros/runtime-introspect
  summary: A small Python library to seamlessly introspect interpreter features at runtime
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
